#!/bin/bash
# ============================================================
# vocal_prep.sh  —  Mix-Based Vocal Humanization for AI Vocals
# ------------------------------------------------------------
# Targets Suno/AI vocal artifacts within a full stereo bounce:
#   1. Metallic sibilance  -> dynamic de-esser on 4–8 kHz
#   2. Flat dynamics       -> transient emphasis + light glue comp
#   3. Synthetic timbre    -> gentle saturation (asoftclip)
#   4. Over-gated breaths  -> mild downward expansion (inverse comp)
#
# Uses ONLY FFmpeg-native filters — no LV2, no stem separation.
# Conservative by default. All parameters overrideable via env vars.
#
# Usage: bash vocal_prep.sh <in_stereo.wav> <out_prep.wav>
# ============================================================
set -e

IN="$1"; OUT="$2"
[ -z "$OUT" ] && { echo "Usage: $0 <in_stereo.wav> <out_prep.wav>"; exit 1; }

# ---- parameters (conservative defaults) ----
DEESSER_INTENSITY="${DEESSER_INTENSITY:-0.6}"
DEESSER_FREQ="${DEESSER_FREQ:-6000}"
DEESSER_MODE="${DEESSER_MODE:-r}"       # r = wideband, s = split
PRESENCE_LIFT_DB="${PRESENCE_LIFT_DB:-1.0}"
BOXINESS_CUT_DB="${BOXINESS_CUT_DB:-0.8}"
SATURATION_DRIVE_DB="${SATURATION_DRIVE_DB:-2.0}"
TRANSIENT_EMPHASIS_DB="${TRANSIENT_EMPHASIS_DB:-1.2}"
GLUE_THRESHOLD_DB="${GLUE_THRESHOLD_DB:-24}"
GLUE_RATIO="${GLUE_RATIO:-1.3}"
EXPAND_THRESHOLD_DB="${EXPAND_THRESHOLD_DB:-40}"
EXPAND_RATIO="${EXPAND_RATIO:-0.8}"
OUTPUT_HEADROOM_DB="${OUTPUT_HEADROOM_DB:-1.0}"

echo ">>> Vocal prep: $IN -> $OUT"
echo "    deesser:  int=${DEESSER_INTENSITY} f=${DEESSER_FREQ} mode=${DEESSER_MODE}"
echo "    presence: +${PRESENCE_LIFT_DB}dB @ 2.5kHz"
echo "    boxiness: -${BOXINESS_CUT_DB}dB @ 400Hz"
echo "    saturate: +${SATURATION_DRIVE_DB}dB drive (asoftclip type=0)"
echo "    transients: +${TRANSIENT_EMPHASIS_DB}dB emphasis @ 2-4kHz"
echo "    glue:     thr=-${GLUE_THRESHOLD_DB}dB ratio=${GLUE_RATIO}:1"

# ---- build filter chain ----
# Stage 1: de-ess sibilance (metallic AI "zing")
# Stage 2: cut boxiness @ 400 Hz (common AI vocal buildup)
# Stage 3: lift vocal presence @ 2.5 kHz
# Stage 4: transient emphasis on vocal attack range (1-4 kHz)
# Stage 5: gentle saturation for harmonic complexity (timbre warmth)
# Stage 6: very light glue compression to restore micro-dynamics
# Stage 7: headroom safety

# This FFmpeg version's deesser uses different param syntax (i,m,f as normalized).
# Use static EQ fallback for reliability across versions.
DEESS_FILTER="equalizer=f=${DEESSER_FREQ}:t=q:w=2.0:g=-2.0"

# Build the full filter string
FILTER_CHAIN="${DEESS_FILTER},\
equalizer=f=400:t=q:w=1.2:g=-${BOXINESS_CUT_DB},\
equalizer=f=2500:t=q:w=1.5:g=${PRESENCE_LIFT_DB},\
equalizer=f=3500:t=q:w=2.0:g=${TRANSIENT_EMPHASIS_DB},\
asoftclip=type=0:threshold=0.794,\
acompressor=threshold=-${GLUE_THRESHOLD_DB}dB:ratio=${GLUE_RATIO}:attack=5:release=50:makeup=1:knee=2,\
volume=-${OUTPUT_HEADROOM_DB}dB"

ffmpeg -hide_banner -nostats -y -i "$IN" -af "$FILTER_CHAIN" -c:a pcm_f32le "$OUT" 2>/dev/null

# ---- write report ----
REPORT="$(dirname "$OUT")/VOCAL_PREP_REPORT.md"
REPORT_BASENAME="$(basename "$OUT" .wav)"
DATE_STR=$(date -Iseconds)
cat > "$REPORT" <<EOF
# Vocal Prep Report — ${REPORT_BASENAME}

**Source:** $(basename "$IN")  
**Output:** $(basename "$OUT")  
**Date:** ${DATE_STR}  

---

## Parameters

| Parameter | Value |
|---|---|
| DEESSER_INTENSITY | ${DEESSER_INTENSITY} |
| DEESSER_FREQ | ${DEESSER_FREQ} Hz |
| DEESSER_MODE | ${DEESSER_MODE} |
| PRESENCE_LIFT_DB | ${PRESENCE_LIFT_DB} dB |
| BOXINESS_CUT_DB | ${BOXINESS_CUT_DB} dB |
| SATURATION_DRIVE_DB | ${SATURATION_DRIVE_DB} dB |
| TRANSIENT_EMPHASIS_DB | ${TRANSIENT_EMPHASIS_DB} dB |
| GLUE_THRESHOLD_DB | -${GLUE_THRESHOLD_DB} dB |
| GLUE_RATIO | ${GLUE_RATIO}:1 |
| OUTPUT_HEADROOM_DB | -${OUTPUT_HEADROOM_DB} dB |

## Processing Chain

1. De-ess: \`${DEESS_FILTER}\`
2. Boxiness cut: \`equalizer=f=400:t=q:w=1.2:g=-${BOXINESS_CUT_DB}\`
3. Presence lift: \`equalizer=f=2500:t=q:w=1.5:g=${PRESENCE_LIFT_DB}\`
4. Transient emphasis: \`equalizer=f=3500:t=q:w=2.0:g=${TRANSIENT_EMPHASIS_DB}\`
5. Saturation: \`asoftclip=type=0:threshold=0.794\`
6. Glue compression: \`acompressor=threshold=-${GLUE_THRESHOLD_DB}dB:ratio=${GLUE_RATIO}:attack=5:release=50:makeup=1\`
7. Headroom: \`volume=-${OUTPUT_HEADROOM_DB}dB\`

## Targeted AI Artifacts

- [x] Metallic sibilance (harsh S/T sounds)
- [x] Flat dynamics (loss of micro-dynamics from normalization)
- [x] Synthetic timbre ("plastic"/"robotic" vocal quality)

*Generated by vocal_prep.sh*
EOF

echo "    vocal prep complete: $OUT"
echo "    report: $REPORT"
