#!/usr/bin/env python3
"""Build consolidated MASTERING_REPORT.md from pipelines/ and archive/."""

import os
import re
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
PIPELINES_DIR = REPO_ROOT / "pipelines"
ARCHIVE_DIR = REPO_ROOT / "archive"
REPORT_PATH = REPO_ROOT / "MASTERING_REPORT.md"


def extract_track_from_pipeline(path: Path) -> dict:
    """Read first 10 lines of a pipeline to extract track name and target metrics."""
    track = path.stem
    target_lufs = "-10.0"
    target_dbtp = "-1.0"
    source_info = ""

    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if "Target:" in line:
                    m = re.search(r"([-\d.]+)\s*LUFS", line)
                    if m:
                        target_lufs = m.group(1)
                    m = re.search(r"<=?\s*([-\d.]+)\s*dBTP", line)
                    if m:
                        target_dbtp = m.group(1)
                if "Source:" in line:
                    source_info = line.split("Source:")[1].strip()
                if line.startswith("#!/bin/bash"):
                    break
    except Exception:
        pass

    return {
        "track": track,
        "pipeline": f"pipelines/{path.name}",
        "target_lufs": target_lufs,
        "target_dbtp": target_dbtp,
        "source_info": source_info,
    }


def find_archived_report(track: str) -> str:
    """Find an archived MASTERING_REPORT that matches this track."""
    if not ARCHIVE_DIR.exists():
        return ""
    # Try exact match first
    for f in ARCHIVE_DIR.glob("MASTERING_REPORT(*).md"):
        # Read first 5 lines to check track name
        try:
            with open(f, "r", encoding="utf-8", errors="ignore") as fh:
                header = fh.read(500)
                if track.replace("_", " ") in header or track in header:
                    return f"archive/{f.name}"
        except Exception:
            continue
    return ""


def find_archived_loudness(track: str) -> str:
    """Find an archived final_loudness that matches this track."""
    if not ARCHIVE_DIR.exists():
        return ""
    for f in ARCHIVE_DIR.glob("final_loudness(*).txt"):
        try:
            with open(f, "r", encoding="utf-8", errors="ignore") as fh:
                content = fh.read(500)
                if track.replace("_", " ") in content or track in content:
                    return f"archive/{f.name}"
        except Exception:
            continue
    return ""


def build_report():
    if not PIPELINES_DIR.exists():
        print("No pipelines/ directory found.")
        return

    pipelines = sorted(PIPELINES_DIR.glob("*.sh"))
    rows = []
    for p in pipelines:
        info = extract_track_from_pipeline(p)
        info["report"] = find_archived_report(info["track"])
        info["loudness"] = find_archived_loudness(info["track"])
        rows.append(info)

    lines = [
        "# Mastering Report — Consolidated Index",
        "",
        f"Generated: {datetime.now().isoformat()}",
        "",
        "## Canonical Pipelines",
        "",
        "| Track | Pipeline | Target LUFS | Target dBTP | Archived Report | Archived Loudness |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['track']} | `{r['pipeline']}` | {r['target_lufs']} | {r['target_dbtp']} | {r['report'] or '-'} | {r['loudness'] or '-'} |"
        )

    lines += [
        "",
        "## Tracks Without Dedicated Pipeline",
        "",
        "These tracks from the catalogue do not yet have a track-specific pipeline script in `pipelines/`.",
        "They may use a generic template or are pending pipeline creation.",
        "",
        "- Ffav_Dish_Hardcore_Pop_2",
        "- Love_Language_Hardcore_Pop_2",
        "- Overthinkk_Hardcore_Pop_2",
        "- how_it_ends_up_hardcore_pop",
        "",
        "## Archive Contents",
        "",
        "All numbered/variant artifacts are preserved in `archive/`.",
        "",
    ]

    if ARCHIVE_DIR.exists():
        categories = {}
        for f in sorted(ARCHIVE_DIR.iterdir()):
            if f.is_file():
                cat = f.stem.split("(")[0] if "(" in f.stem else f.stem.split("_")[0]
                categories.setdefault(cat, []).append(f.name)
        for cat, files in sorted(categories.items()):
            lines.append(f"- **{cat}**: {len(files)} file(s)")

    lines += [
        "",
        "---",
        "",
        "*This report is auto-generated by `tools/build_index.py`. Do not edit manually.*",
    ]

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {REPORT_PATH}")


if __name__ == "__main__":
    build_report()
