#!/usr/bin/env python3
"""Regenerate CATALOGUE.md reflecting archive/, pipelines/, and root layout."""

import os
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
CATALOGUE_PATH = REPO_ROOT / "CATALOGUE.md"


def collect_files(directory: Path, prefix="") -> list:
    """Collect files in directory, returning (relative_path, size_bytes)."""
    results = []
    if not directory.exists():
        return results
    for f in sorted(directory.iterdir()):
        rel = f"{prefix}/{f.name}" if prefix else f.name
        if f.is_file():
            results.append((rel, f.stat().st_size))
        elif f.is_dir() and f.name not in {".git", "archive", "pipelines", "__pycache__"}:
            results.extend(collect_files(f, rel))
    return results


def format_size(size: int) -> str:
    if size < 1024:
        return f"{size} B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.2f} KB"
    else:
        return f"{size / (1024 * 1024):.2f} MB"


def build_catalogue():
    lines = [
        "# Mastering Toolshop Catalogue",
        "",
        f"Generated: {datetime.now().isoformat()}",
        "",
        "This catalogue reflects the post-Phase-0 layout:",
        "- `pipelines/` — canonical per-track mastering pipelines",
        "- `archive/` — historical numbered/variant artifacts",
        "- `tools/` — index generation and utility scripts",
        "- Root — functional scripts, documentation, and active deliverables",
        "",
    ]

    # Pipelines
    pipelines = collect_files(REPO_ROOT / "pipelines")
    if pipelines:
        lines += [
            "## Canonical Pipelines (`pipelines/`)",
            "",
            "| Pipeline | Size |",
            "|---|---|",
        ]
        for name, size in pipelines:
            lines.append(f"| `{name}` | {format_size(size)} |")
        lines.append("")

    # Archive
    archive = collect_files(REPO_ROOT / "archive")
    if archive:
        lines += [
            "## Archive (`archive/`)",
            "",
            "| File | Size |",
            "|---|---|",
        ]
        for name, size in archive:
            lines.append(f"| `{name}` | {format_size(size)} |")
        lines.append("")

    # Root tools
    tools = collect_files(REPO_ROOT / "tools")
    if tools:
        lines += [
            "## Tools (`tools/`)",
            "",
            "| File | Size |",
            "|---|---|",
        ]
        for name, size in tools:
            lines.append(f"| `{name}` | {format_size(size)} |")
        lines.append("")

    # Root files (excluding archive, pipelines, tools)
    root_files = []
    for f in sorted(REPO_ROOT.iterdir()):
        if f.is_file() and f.name != "CATALOGUE.md":
            root_files.append((f.name, f.stat().st_size))
    if root_files:
        lines += [
            "## Root Directory — Functional Scripts & Documentation",
            "",
            "| File | Size |",
            "|---|---|",
        ]
        for name, size in root_files:
            lines.append(f"| `{name}` | {format_size(size)} |")
        lines.append("")

    lines += [
        "---",
        "",
        "*Auto-generated by `tools/regenerate_catalogue.py`. Do not edit manually.*",
    ]

    with open(CATALOGUE_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {CATALOGUE_PATH}")


if __name__ == "__main__":
    build_catalogue()
